/**
 * Generates the Claude Code files whose format differs from what the harness
 * authors. Pure functions: they take content and return {path, content} pairs,
 * so the same code produces the install and the drift check in doctor.
 *
 * Less is generated here than for Kiro. Claude Code reads SKILL.md in the shape
 * the harness already writes, so skills are linked, not wrapped. What is left
 * are the four surfaces whose format genuinely differs - agents, commands,
 * hooks and MCP - plus the one-line CLAUDE.md that points at AGENTS.md.
 */
import fs from 'node:fs';
import path from 'node:path';
import { parseFrontmatter } from './frontmatter.mjs';
import { harnessPath } from './paths.mjs';

const GENERATED_BY = 'Generated by the harness. Edit the file it points at, not this one.';

/**
 * VS Code tool names to Claude Code tool names. A name outside this map is
 * dropped rather than approximated: an agent holding the wrong tool is worse
 * than one missing a tool, and the drop is reported by doctor.
 *
 * `problems` is deliberately empty. Claude Code has no diagnostics tool; the
 * equivalent is running the linter through Bash, which every agent that asks
 * for `problems` already asks for via runCommands or editFiles.
 */
export const TOOL_MAP = {
  codebase: ['Read', 'Grep', 'Glob'],
  search: ['Grep'],
  usages: ['Grep'],
  changes: ['Bash'],
  runCommands: ['Bash'],
  editFiles: ['Edit', 'Write'],
  agent: ['Task'],
  problems: [],
};

/** Model aliases Claude Code accepts. An unrecognised name yields no field. */
const MODEL_ALIASES = ['sonnet', 'opus', 'haiku'];

/**
 * Hook matchers name tools, and Claude Code compares them case-sensitively:
 * `write` never matches `Write`. Carrying the VS Code matchers across
 * unchanged would install guardrails that can never fire, which is worse than
 * installing none - so each one is translated, and a matcher with no
 * translation is dropped and reported rather than guessed at.
 */
export const MATCHER_MAP = {
  'readFile|read_file|read|view|open|cat|fetch|textSearch|fileSearch': 'Read|Grep|Glob|WebFetch',
  'editFiles|createFile|str_replace|write|edit': 'Edit|Write|NotebookEdit',
  'runCommands|runInTerminal|bash|shell': 'Bash',
};

/**
 * Claude Code resolves a hook command from a working directory it does not
 * promise, so paths go through the placeholder it substitutes for the project
 * root rather than being relative.
 */
const CLAUDE_SCRIPTS = '${CLAUDE_PROJECT_DIR}/.claude/harness/hooks/scripts/';

/** The prefix that marks a hook entry in settings.json as the harness's own. */
export const HARNESS_HOOK_MARK = CLAUDE_SCRIPTS;

const listDir = (dir) => (fs.existsSync(dir) ? fs.readdirSync(dir, { withFileTypes: true }) : []);

/**
 * Source order is preserved and duplicates collapse, so `codebase, search`
 * becomes `Read, Grep, Glob` rather than repeating Grep.
 */
export function mapTools(tools) {
  const mapped = [];
  for (const tool of tools ?? []) {
    for (const name of TOOL_MAP[tool] ?? []) {
      if (!mapped.includes(name)) mapped.push(name);
    }
  }
  return mapped;
}

/**
 * Tool names the map has never heard of. `problems` is not one of them: it is
 * in the map with no equivalent, which is a decision already made and written
 * down. This reports the other case - somebody added a tool to an agent and
 * the translation silently dropped it.
 */
export function unmappedTools(tools) {
  return (tools ?? []).filter((tool) => !(tool in TOOL_MAP));
}

/** The agents whose front matter names a tool the translation cannot place. */
export function agentsWithUnmappedTools() {
  const root = harnessPath('core/agents');
  return listDir(root)
    .filter((e) => e.isFile() && e.name.endsWith('.agent.md'))
    .map((entry) => {
      const { data } = parseFrontmatter(fs.readFileSync(path.join(root, entry.name), 'utf8'));
      return { name: entry.name.replace('.agent.md', ''), tools: unmappedTools(data.tools) };
    })
    .filter((agent) => agent.tools.length > 0);
}

/**
 * The source lists model names for the VS Code picker, across vendors. The
 * first one that names a Claude tier becomes the alias; anything else means no
 * field at all, so the agent runs on the session's model instead of one the
 * harness invented.
 */
export function modelAlias(models) {
  const list = Array.isArray(models) ? models : [models];
  for (const entry of list) {
    const found = MODEL_ALIASES.find((alias) =>
      new RegExp(`claude\\s+${alias}`, 'i').test(String(entry ?? ''))
    );
    if (found) return found;
  }
  return null;
}

/**
 * A YAML scalar that reads back as written. Only quoted when it has to be: a
 * description containing ": " is ambiguous YAML and would corrupt the front
 * matter of the generated file, which nothing downstream validates.
 */
export function frontMatterValue(key, value) {
  const text = String(value);
  const needsQuotes = /:\s|^[\s>|&*!%@`{}[\],#"']|\s$/.test(text);
  return needsQuotes ? `"${text.split('\\').join('\\\\').split('"').join('\\"')}"` : text;
}

function frontMatter(fields) {
  const lines = ['---'];
  for (const [key, value] of Object.entries(fields)) {
    if (value === undefined || value === null || value === '') continue;
    lines.push(`${key}: ${frontMatterValue(key, value)}`);
  }
  lines.push('---');
  return lines.join('\n');
}

/**
 * One subagent per agent file. Only the front matter is translated - the six
 * sections below it are already a system prompt, and rewriting prose is how a
 * generated copy starts saying something the source does not.
 */
export function claudeAgents() {
  const root = harnessPath('core/agents');
  return listDir(root)
    .filter((e) => e.isFile() && e.name.endsWith('.agent.md'))
    .map((entry) => {
      const name = entry.name.replace('.agent.md', '');
      const { data, body } = parseFrontmatter(fs.readFileSync(path.join(root, entry.name), 'utf8'));
      // An agent that asked for tools but whose tools all map to nothing
      // cannot be written: omitting the field makes Claude Code inherit every
      // tool there is, which is the opposite of the restriction the agent
      // declared, and the worst outcome this translation can produce. So the
      // agent is skipped and doctor names it.
      if ((data.tools ?? []).length > 0 && mapTools(data.tools).length === 0) return null;
      return {
        path: `.claude/agents/${name}.md`,
        content: [
          frontMatter({
            name: data.name ?? name,
            description: data.description ?? '',
            tools: mapTools(data.tools).join(', '),
            model: modelAlias(data.model),
          }),
          '',
          `<!-- ${GENERATED_BY} -->`,
          body.startsWith('\n') ? body.slice(1) : body,
        ].join('\n'),
      };
    })
    .filter(Boolean);
}

/** Agents no subagent can be written for, because their tools do not translate. */
export function agentsWithNoTools() {
  const root = harnessPath('core/agents');
  return listDir(root)
    .filter((e) => e.isFile() && e.name.endsWith('.agent.md'))
    .map((entry) => {
      const { data } = parseFrontmatter(fs.readFileSync(path.join(root, entry.name), 'utf8'));
      return { name: entry.name.replace('.agent.md', ''), tools: data.tools ?? [] };
    })
    .filter((agent) => agent.tools.length > 0 && mapTools(agent.tools).length === 0);
}

/**
 * One slash command per prompt. The body carries a VS Code input variable,
 * `${input:request}`, which Claude Code spells `$ARGUMENTS`; the variable's own
 * name is worth keeping as the argument hint, since it is the only place the
 * prompt says what it expects to be given.
 */
export function claudeCommands() {
  const root = harnessPath('core/prompts');
  return listDir(root)
    .filter((e) => e.isFile() && e.name.endsWith('.prompt.md'))
    .map((entry) => {
      const name = entry.name.replace('.prompt.md', '');
      const { data, body } = parseFrontmatter(fs.readFileSync(path.join(root, entry.name), 'utf8'));
      const variables = [...body.matchAll(/\$\{input:([A-Za-z0-9_-]+)\}/g)].map((m) => m[1]);
      return {
        path: `.claude/commands/${name}.md`,
        content: [
          frontMatter({
            description: data.description ?? '',
            'argument-hint': data['argument-hint'] ?? variables[0] ?? null,
          }),
          '',
          `<!-- ${GENERATED_BY} -->`,
          body.replace(/\$\{input:[A-Za-z0-9_-]+\}/g, '$ARGUMENTS').replace(/^\n/, ''),
        ].join('\n'),
      };
    });
}

/**
 * The harness hook file becomes Claude Code's shape: one entry per event, each
 * a list of matcher groups wrapping their own hooks array.
 *
 * Two differences from the source worth naming. A hook entry has no env field,
 * so the mode that tells the scripts to read stdin travels in argv, the same
 * way and for the same reason it does under Kiro. And matchers are translated
 * rather than copied, because they name tools and Claude Code's tool names are
 * neither the VS Code ones nor case-insensitive.
 *
 * The manifest is a parameter so the self-test can translate a matcher the
 * shipped file does not currently carry: the guardrails run unmatched through
 * one dispatcher today, and the translation still has to be right the day a
 * matched entry comes back.
 */
export function claudeHooks(manifest = null) {
  let parsed = manifest;
  if (!parsed) {
    const source = harnessPath('core/hooks/harness.json');
    if (!fs.existsSync(source)) return { hooks: {}, dropped: [] };
    parsed = JSON.parse(fs.readFileSync(source, 'utf8'));
  }
  const hooks = {};
  const dropped = [];

  for (const [event, entries] of Object.entries(parsed.hooks ?? {})) {
    const groups = [];
    for (const entry of entries) {
      const matcher = entry.matcher ? MATCHER_MAP[entry.matcher] : undefined;
      if (entry.matcher && !matcher) {
        dropped.push(`${event}:${entry.matcher}`);
        continue;
      }
      const command =
        String(entry.command ?? '').replace('.github/hooks/scripts/', CLAUDE_SCRIPTS) +
        ' --hook-mode=claude';

      // Same event and same matcher is one group with two hooks, which is how
      // Claude Code expects to read it and how it reports them back.
      const existing = groups.find((g) => g.matcher === matcher);
      const hook = { type: 'command', command, ...(entry.timeout ? { timeout: entry.timeout } : {}) };
      if (existing) existing.hooks.push(hook);
      else groups.push({ ...(matcher ? { matcher } : {}), hooks: [hook] });
    }
    if (groups.length > 0) hooks[event] = groups;
  }

  return { hooks, dropped };
}

const isHarnessHook = (hook) => String(hook?.command ?? '').includes(HARNESS_HOOK_MARK);

/** A group with its harness hooks taken out, or null when nothing else is left. */
function withoutHarnessHooks(group) {
  const kept = (group.hooks ?? []).filter((hook) => !isHarnessHook(hook));
  return kept.length > 0 ? { ...group, hooks: kept } : null;
}

/**
 * Adds the harness's hook entries to a settings file the repository may
 * already own, and changes nothing else.
 *
 * The harness is not the owner of .claude/settings.json: a repository that
 * already uses Claude Code keeps its permissions, its model and possibly its
 * own hooks there. So the merge is by subtraction and addition rather than by
 * replacement - every entry the harness wrote before is removed by its command
 * prefix and the fresh ones are appended, which is also what makes reinstalling
 * idempotent instead of duplicating.
 */
export function mergeSettings(existing, hooks) {
  const merged = { ...(existing ?? {}) };
  const events = { ...(merged.hooks ?? {}) };

  // The union, not just the fresh events. An event the harness used to write
  // and no longer does has to lose its entries here, or nothing ever removes
  // them: reinstalling would not, and the drift check cannot see it, because
  // the stale entry carries the same marker on both sides of the comparison.
  for (const event of new Set([...Object.keys(events), ...Object.keys(hooks)])) {
    const theirs = (events[event] ?? []).map(withoutHarnessHooks).filter(Boolean);
    const groups = [...theirs, ...(hooks[event] ?? [])];
    if (groups.length > 0) events[event] = groups;
    else delete events[event];
  }

  merged.hooks = events;
  return merged;
}

/**
 * Only the entries the harness wrote, which is the unit doctor hashes. The
 * whole file cannot be hashed: the keys around it belong to somebody else and
 * change without the harness drifting.
 */
export function harnessHookSlice(settings) {
  const slice = {};
  for (const [event, groups] of Object.entries(settings?.hooks ?? {})) {
    const mine = (groups ?? [])
      .map((group) => {
        const hooks = (group.hooks ?? []).filter(isHarnessHook);
        return hooks.length > 0 ? { ...group, hooks } : null;
      })
      .filter(Boolean);
    if (mine.length > 0) slice[event] = mine;
  }
  return slice;
}

/**
 * The file as it was before the harness touched it. An event left with no
 * groups, and a hooks key left with no events, are removed rather than left
 * behind empty, so a file the harness created from nothing ends up `{}` and
 * the caller can tell it is safe to delete.
 */
export function stripHarnessHooks(settings) {
  const stripped = { ...(settings ?? {}) };
  const events = {};

  for (const [event, groups] of Object.entries(stripped.hooks ?? {})) {
    const kept = (groups ?? []).map(withoutHarnessHooks).filter(Boolean);
    if (kept.length > 0) events[event] = kept;
  }

  if (Object.keys(events).length > 0) stripped.hooks = events;
  else delete stripped.hooks;
  return stripped;
}

/**
 * The harness authors MCP servers in the shape VS Code reads, under `servers`,
 * with four fields that exist for a human to decide with - owner, trust, scope
 * and version - and a `disabled` bucket that is deliberately not configuration.
 * Claude Code reads `mcpServers`, so this is a real translation: enabled
 * servers only, and only the fields that are actually configuration.
 */
export function claudeMcp(source) {
  const mcpServers = {};
  for (const [name, server] of Object.entries(source?.servers ?? {})) {
    const { owner, trust, scope, version, ...config } = server;
    mcpServers[name] = config;
  }
  // No $comment here, unlike every other file the harness writes: this one is
  // parsed by a tool whose schema the harness does not own, and a marker that
  // might trip validation is not worth the note it carries.
  return {
    path: '.mcp.json',
    content: `${JSON.stringify({ mcpServers }, null, 2)}\n`,
  };
}

/**
 * Claude Code reads CLAUDE.md and does not fall back to AGENTS.md, so the file
 * has to exist - but it imports rather than duplicates, the same way Kiro's
 * steering files point at the linked original instead of copying it.
 */
export function claudeMd() {
  return {
    path: 'CLAUDE.md',
    content: `<!-- Generated by the harness. Edit AGENTS.md, not this file. -->\n@AGENTS.md\n`,
  };
}

/**
 * Everything a Claude target generates, in one list.
 *
 * .claude/settings.json is deliberately absent: it is merged into rather than
 * generated, because the repository may own keys in it that the harness must
 * not carry away. install and doctor handle it through mergeSettings and
 * harnessHookSlice instead.
 */
export function generatedFiles() {
  const mcpSource = harnessPath('core/mcp.json');
  const mcp = fs.existsSync(mcpSource) ? [claudeMcp(JSON.parse(fs.readFileSync(mcpSource, 'utf8')))] : [];
  return [...claudeAgents(), ...claudeCommands(), ...mcp, claudeMd()];
}
