/**
 * Generates the few Kiro files whose format differs from what the harness
 * authors. Pure functions: they take content and return {path, content} pairs,
 * so the same code produces the install and the drift check in doctor.
 *
 * Everything here is thin on purpose. A steering file is front matter plus one
 * include line; the content it points at is the linked original, so editing a
 * skill in the harness is still live everywhere with no regeneration.
 */
import fs from 'node:fs';
import path from 'node:path';
import { parseFrontmatter } from './frontmatter.mjs';
import { harnessPath } from './paths.mjs';
import { TARGETS } from './targets.mjs';

const GENERATED_BY = 'Generated by the harness. Edit the file it points at, not this one.';

/**
 * Kiro reads one event name where the harness writes another, and has no
 * equivalent for three of them. Absent entries are dropped and reported rather
 * than mapped onto something close, because a guardrail on the wrong event is
 * worse than a guardrail everyone knows is missing.
 */
export const KIRO_EVENT = {
  SessionStart: 'SessionStart',
  UserPromptSubmit: 'PromptSubmit',
  PreToolUse: 'PreToolUse',
  PostToolUse: 'PostToolUse',
  Stop: 'AgentStop',
};

export const UNMAPPED_EVENTS = TARGETS.kiro.unmappedEvents;

/**
 * Triggers Kiro has and the harness has no name for. PostTaskExecution closes
 * exactly one spec task, which is a better moment to collect a dream than the
 * end of a whole agent turn - so the collector runs on both, and its own state
 * file keeps the second run silent.
 */
const KIRO_EXTRA = [
  { script: 'dream-collect.mjs', args: '--hook', trigger: 'PostTaskExecution' },
];

const listDir = (dir) => (fs.existsSync(dir) ? fs.readdirSync(dir, { withFileTypes: true }) : []);

/** A YAML scalar that Kiro reads back as written. */
const quote = (value) => `"${String(value).split('"').join('\\"')}"`;

function frontMatter(fields) {
  const lines = ['---'];
  for (const [key, value] of Object.entries(fields)) {
    if (value === undefined || value === null) continue;
    lines.push(Array.isArray(value) ? `${key}: [${value.map(quote).join(', ')}]` : `${key}: ${value}`);
  }
  lines.push('---');
  return lines.join('\n');
}

/**
 * applyTo is a comma-separated glob list; fileMatchPattern takes one glob or an
 * array. A missing or match-everything glob becomes inclusion: always, which is
 * how Kiro spells the same thing.
 */
function inclusionFor(applyTo) {
  const globs = String(applyTo ?? '')
    .split(',')
    .map((g) => g.trim().replace(/^["']|["']$/g, ''))
    .filter(Boolean);

  if (globs.length === 0 || globs.every((g) => g === '**' || g === '**/*')) {
    return { inclusion: 'always' };
  }
  return { inclusion: 'fileMatch', fileMatchPattern: globs.length === 1 ? quote(globs[0]) : globs };
}

/** One steering file per instruction, carrying the glob across. */
export function steeringForInstructions() {
  const root = harnessPath('core/instructions');
  return listDir(root)
    .filter((e) => e.isFile() && e.name.endsWith('.instructions.md'))
    .map((entry) => {
      const name = entry.name.replace('.instructions.md', '');
      const { data } = parseFrontmatter(fs.readFileSync(path.join(root, entry.name), 'utf8'));
      return {
        path: `.kiro/steering/${name}.md`,
        content: [
          frontMatter(inclusionFor(data.applyTo)),
          '',
          `<!-- ${GENERATED_BY} -->`,
          '',
          `#[[file:.kiro/harness/instructions/${entry.name}]]`,
          '',
        ].join('\n'),
      };
    });
}

/**
 * One steering file per skill, set to manual so it costs nothing until it is
 * asked for. The name and description come from the skill, which is what makes
 * it findable in Kiro without loading the body.
 */
export function steeringForSkills() {
  const root = harnessPath('core/skills');
  return listDir(root)
    .filter((e) => e.isDirectory())
    .map((entry) => ({ entry, file: path.join(root, entry.name, 'SKILL.md') }))
    .filter(({ file }) => fs.existsSync(file))
    .map(({ entry, file }) => {
      const { data } = parseFrontmatter(fs.readFileSync(file, 'utf8'));
      return {
        path: `.kiro/steering/skill-${entry.name}.md`,
        content: [
          frontMatter({
            inclusion: 'manual',
            name: quote(data.name ?? entry.name),
            description: quote(data.description ?? ''),
          }),
          '',
          `<!-- ${GENERATED_BY} -->`,
          '',
          `#[[file:.kiro/harness/skills/${entry.name}/SKILL.md]]`,
          '',
        ].join('\n'),
      };
    });
}

/**
 * The harness hook file keyed by event becomes Kiro's flat list. The command is
 * repointed at the linked scripts and carries --hook-mode, because Kiro's hook
 * schema has no env field and the scripts refuse to read stdin without a mode.
 */
export function kiroHooks() {
  const source = harnessPath('core/hooks/harness.json');
  if (!fs.existsSync(source)) return { hooks: [], dropped: [] };

  const parsed = JSON.parse(fs.readFileSync(source, 'utf8'));
  const hooks = [];
  const dropped = [];

  for (const [event, entries] of Object.entries(parsed.hooks ?? {})) {
    const trigger = KIRO_EVENT[event];
    if (!trigger) {
      dropped.push(event);
      continue;
    }
    for (const entry of entries) {
      const command = String(entry.command ?? '').replace('.github/hooks/', '.kiro/harness/hooks/');
      const script = command.split(' ').find((part) => part.endsWith('.mjs')) ?? command;
      hooks.push({
        name: `harness-${path.basename(script, '.mjs')}-${trigger}`.toLowerCase(),
        trigger,
        ...(entry.matcher ? { matcher: entry.matcher } : {}),
        action: { type: 'command', command: `${command} --hook-mode=kiro` },
      });
    }
  }
  for (const extra of KIRO_EXTRA) {
    const command = 'node .kiro/harness/hooks/scripts/' + extra.script + ' ' + extra.args;
    hooks.push({
      name: ('harness-' + extra.script.replace('.mjs', '') + '-' + extra.trigger).toLowerCase(),
      trigger: extra.trigger,
      action: { type: 'command', command: command + ' --hook-mode=kiro' },
    });
  }

  return { hooks, dropped };
}

export function kiroHooksFile() {
  const { hooks } = kiroHooks();
  return {
    path: '.kiro/hooks/harness.json',
    content: `${JSON.stringify({ version: 'v1', $comment: GENERATED_BY, hooks }, null, 2)}\n`,
  };
}

/** Everything a Kiro target generates, in one list. */
export function generatedFiles() {
  return [...steeringForInstructions(), ...steeringForSkills(), kiroHooksFile()];
}
