#!/usr/bin/env node
/**
 * Deterministic half of the repository inventory.
 *
 * Everything a script can establish without a model costs zero tokens and is
 * reproducible: the stack, the commands, the module map, the entry points, the
 * size of things. The skill fills in the judgement afterwards.
 *
 *   node .github/skills/codebase-inventory/scripts/inventory.mjs > specs/_context.md
 */
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';

const IGNORED = new Set([
  'node_modules', '.git', 'dist', 'build', 'out', 'bin', 'obj', 'vendor',
  '.venv', 'venv', '__pycache__', 'target', '.next', '.nuxt', 'coverage', '.harness',
]);

const root = process.argv[2] ?? process.cwd();
const rel = (p) => path.relative(root, p).split(path.sep).join('/');

function git(args, fallback = '') {
  try {
    return execFileSync('git', args, { cwd: root, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
  } catch {
    return fallback;
  }
}

function walk(dir, depth = 0, acc = []) {
  if (depth > 3) return acc;
  let entries;
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch {
    return acc;
  }
  for (const entry of entries) {
    if (IGNORED.has(entry.name)) continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full, depth + 1, acc);
    else if (entry.isFile()) acc.push(full);
  }
  return acc;
}

const files = walk(root);
const byExt = new Map();
for (const file of files) {
  const ext = path.extname(file).toLowerCase() || '(none)';
  byExt.set(ext, (byExt.get(ext) ?? 0) + 1);
}

const MANIFESTS = [
  ['package.json', 'Node'], ['tsconfig.json', 'TypeScript'], ['pyproject.toml', 'Python'],
  ['requirements.txt', 'Python'], ['go.mod', 'Go'], ['Cargo.toml', 'Rust'],
  ['pom.xml', 'Java (Maven)'], ['build.gradle', 'Java (Gradle)'], ['CMakeLists.txt', 'C++'],
  ['Dockerfile', 'Docker'], ['template.yaml', 'CloudFormation or SAM'],
  ['cdk.json', 'AWS CDK'], ['serverless.yml', 'Serverless Framework'],
  ['Chart.yaml', 'Helm'], ['kustomization.yaml', 'Kustomize'],
];

const present = MANIFESTS.filter(([f]) => fs.existsSync(path.join(root, f)));
const byGlob = [
  ['.csproj', '.NET project'], ['.sln', '.NET solution'], ['.fsproj', 'F# project'],
  ['.tf', 'Terraform'], ['.bicep', 'Bicep'], ['.tsx', 'React'], ['.vue', 'Vue'],
].map(([ext, name]) => [name, files.filter((file) => file.endsWith(ext)).length])
  .filter(([, n]) => n > 0);

const terraform = files.filter((f) => f.endsWith('.tf')).length;
const k8sManifests = files.filter((f) => /\.ya?ml$/.test(f) && /(deployment|service|ingress|configmap|statefulset)/i.test(path.basename(f))).length;

function npmScripts() {
  try {
    const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
    return Object.entries(pkg.scripts ?? {});
  } catch {
    return [];
  }
}

function topModules() {
  const src = ['src', 'lib', 'app', 'internal', 'pkg', 'cmd', 'services', 'packages', 'infra', 'terraform', 'charts']
    .map((d) => path.join(root, d))
    .filter((d) => fs.existsSync(d));
  const base = src.length > 0 ? src : [root];
  const out = [];
  for (const dir of base) {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (!entry.isDirectory() || IGNORED.has(entry.name)) continue;
      const count = walk(path.join(dir, entry.name)).length;
      out.push({ module: rel(path.join(dir, entry.name)), files: count });
    }
  }
  return out.sort((a, b) => b.files - a.files).slice(0, 20);
}

const lines = [];
const say = (s = '') => lines.push(s);

say('# Repository context');
say();
say('Generated by the codebase-inventory script. The sections marked TODO need a');
say('human or an agent to fill in: a script can count files, it cannot tell you');
say('what breaks if this service stops.');
say();
say(`generated: ${new Date().toISOString().slice(0, 10)}`);
say(`commit: ${git(['rev-parse', '--short', 'HEAD'], 'unknown')}`);
say(`branch: ${git(['rev-parse', '--abbrev-ref', 'HEAD'], 'unknown')}`);
say(`tracked files: ${files.length}`);
say();
say('## What this repository is');
say();
say('TODO: two or three sentences. What it does, who runs it, what breaks if it stops.');
say();
say('## Stack');
say();
say('| signal | detected |');
say('|---|---|');
for (const [file, name] of present) say(`| ${file} | ${name} |`);
for (const [name, n] of byGlob) say(`| ${n} files | ${name} |`);
if (k8sManifests > 0) say(`| ${k8sManifests} manifest files | Kubernetes |`);
say();
say('Largest file types:');
say();
say('| extension | files |');
say('|---|---|');
for (const [ext, n] of [...byExt.entries()].sort((a, b) => b[1] - a[1]).slice(0, 8)) {
  say(`| ${ext} | ${n} |`);
}
say();
say('## Commands');
say();
say('| purpose | command |');
say('|---|---|');
const scripts = npmScripts();
if (scripts.length > 0) {
  for (const [name, cmd] of scripts.slice(0, 12)) say(`| ${name} | npm run ${name} | ${cmd.slice(0, 60)} |`.replace(/\|$/, ''));
} else {
  say('| install | TODO |');
  say('| build | TODO |');
  say('| test | TODO |');
  say('| lint | TODO |');
}
say();
say('An agent may only run commands listed here.');
say();
say('## Module map');
say();
say('| module | files | owns |');
say('|---|---|---|');
for (const m of topModules()) say(`| ${m.module} | ${m.files} | TODO |`);
say();
say('## Entry points');
say();
say('TODO: where execution actually begins. The script can list candidates but');
say('cannot tell which one matters.');
say();
say('## Conventions this repository already follows');
say();
say('TODO: observed from the code, not aspirational.');
say();
say('## Landmines');
say();
say('TODO: what looks wrong and is load-bearing, and what looks fine and will break.');
say();

process.stdout.write(lines.join('\n'));
