'use strict';
const legacyStudioRender=render,legacyStudioChat=studioChat;
let proTab='appearance',multiSelection=[],crossFilter=null,pendingAI=null,proSlide=0,draggedWidget=null,draggedField=null;
function pro(d=dash()){
 if(!d.pro){const s=studio(d),widgets={};for(const id of s.order){const v=visual(id,d),o=options(id,d);widgets[id]={...proDefaults(),...o,id,title:v.title,text:v.text||'',type:v.kind==='trend'?(v.type==='bar'?'column':v.type):v.kind==='mix'?v.type:v.kind,dimension:v.kind==='trend'?'month':'category',span:o.wide?12:6};}
 d.pro={version:1,widgets,pages:[{id:'overview',name:'Visão geral',widgets:[...s.order],filters:{}}],activePage:'overview',selected:s.order[0]||'',measures:[],params:{colaboradores:100}};
 const cc={...proDefaults(),id:proId(),title:'Custos por categoria',type:'bar',dimension:'category',span:12};const detail={...proDefaults(),id:proId(),title:'Detalhamento financeiro',type:'table',dimension:'category',span:12};d.pro.widgets[cc.id]=cc;d.pro.widgets[detail.id]=detail;d.pro.pages.push({id:'centers',name:'Centros de custo',widgets:[cc.id],filters:{}},{id:'detail',name:'Detalhamento',widgets:[detail.id],filters:{}});
 }
 return d.pro;
}
function currentPage(d=dash()){const p=pro(d);return p.pages.find(x=>x.id===p.activePage)||p.pages[0];}
function currentWidget(){const p=pro();return p.widgets[p.selected]||p.widgets[currentPage().widgets[0]];}
function choosePage(id){const p=pro();if(!p.pages.some(x=>x.id===id))return;p.activePage=id;p.selected=currentPage().widgets[0]||'';multiSelection=[];crossFilter=null;persist();render();lastSnapshot=JSON.stringify(state);}
function commitPro(message){changed();if(message)toast(message);}
function valueName(key){return {actual:'Realizado',budget:'Orçamento',count:'Registros',none:'Sem comparação'}[key]||pro().measures.find(m=>m.id===key)?.name||'Medida';}
function dimValue(r,key){return key==='month'?r.date.slice(0,7):r[key];}
function labelValue(value,dim){return dim==='month'?periodLabel(value):String(value);}
function effectiveRows(w,page=currentPage(),d=dash(),ignoreCross=false){
 const f={area:d.area,period:d.period,categories:d.categories,...page.filters,...w.filters};
 const allMonths=w.dimension==='month'&&!page.filters.period&&!w.filters.period;
 return sourceRows(d).filter(r=>(allMonths?r.date.slice(0,7)<=f.period:r.date.slice(0,7)===f.period)&&(!f.area||f.area==='*'||f.area==='Todas as áreas'||r.area===f.area)&&(!f.categories?.length||f.categories.includes(r.category))&&(ignoreCross||page.id!==currentPage(d).id||!crossFilter||crossFilter.origin===w.id||dimValue(r,crossFilter.dimension)===crossFilter.value));
}
function aggregateValue(rows,key,w,d=dash()){
 if(key==='none')return null;if(key==='count')return rows.length;
 const measure=pro(d).measures.find(m=>m.id===key);
 if(measure){const values={...pro(d).params,realizado:rows.reduce((a,r)=>a+r.actual,0),orcado:rows.reduce((a,r)=>a+r.budget,0),registros:rows.length};try{return calculateFormula(measure.expression,values);}catch{return null;}}
 const numbers=rows.map(r=>Number(r[key]||0));if(!numbers.length)return 0;
 if(w.aggregation==='count')return numbers.length;if(w.aggregation==='avg')return numbers.reduce((a,b)=>a+b,0)/numbers.length;if(w.aggregation==='min')return Math.min(...numbers);if(w.aggregation==='max')return Math.max(...numbers);return numbers.reduce((a,b)=>a+b,0);
}
function chartData(w,page=currentPage(),d=dash()){
 const rows=effectiveRows(w,page,d),groups=new Map();for(const r of rows){const key=dimValue(r,w.dimension);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(r);}
 let data=[...groups].map(([key,rs])=>({key,label:labelValue(key,w.dimension),value:aggregateValue(rs,w.value,w,d),comparison:aggregateValue(rs,w.comparison,w,d),rows:rs}));
 data.sort(w.sort==='desc'?(a,b)=>(b.value||0)-(a.value||0):w.sort==='asc'?(a,b)=>(a.value||0)-(b.value||0):(a,b)=>String(a.key).localeCompare(String(b.key),'pt-BR'));
 if(w.top)data=data.slice(0,w.top);return data;
}
function numberPro(n,w){if(n===null||!Number.isFinite(n))return '—';const format=w.format||'number',div=w.unit==='mil'?1000:w.unit==='mi'?1e6:1,suffix=w.unit==='mil'?' mil':w.unit==='mi'?' mi':'';return (format==='currency'?'R$ ':'')+(n/div).toLocaleString('pt-BR',{minimumFractionDigits:w.decimals,maximumFractionDigits:w.decimals})+suffix+(format==='percent'?'%':'');}
function markColor(item,w){return w.condition==='budget'&&item.value>item.comparison||w.condition==='target'&&item.value>w.target?w.conditionColor:w.color;}
function hitAttrs(w,item){return `data-pro-hit="${esc(w.id)}" data-hit-value="${esc(item.key)}" tabindex="0" role="button" aria-label="${esc(item.label)}: ${esc(numberPro(item.value,w))}"`;}
function proChart(w,page=currentPage(),d=dash()){
 const data=chartData(w,page,d);if(!data.length)return '<div class="pro-empty">Nenhum registro para estes filtros.</div>';
 if(w.type==='table')return proTable(w,data);
 if(w.type==='waterfall')return proWaterfall(w,data);
 if(w.type==='donut')return proDonut(w,data);
 const seriesKeys=w.legendField!=='none'?[...new Set(data.flatMap(x=>x.rows.map(r=>dimValue(r,w.legendField))))].slice(0,12):[];
 const palette=[w.color,w.comparisonColor,'#078e97','#8b67c5','#bc833b','#7386a2'];
 const series=seriesKeys.length?seriesKeys.map((key,i)=>({name:labelValue(key,w.legendField),color:palette[i%palette.length],values:data.map(x=>aggregateValue(x.rows.filter(r=>dimValue(r,w.legendField)===key),w.value,w,d))})):[{name:valueName(w.value),color:w.color,values:data.map(x=>x.value)},...(w.comparison!=='none'?[{name:valueName(w.comparison),color:w.comparisonColor,values:data.map(x=>x.comparison)}]:[])];
 const values=series.flatMap(s=>s.values).filter(Number.isFinite),min=Math.min(0,...values),max=Math.max(1,...values,w.target||0),span=max-min,pad=span*.15,lo=min<0?min-pad:0,hi=max+pad;
 const horizontal=w.type==='bar',W=640,H=horizontal?Math.max(245,data.length*38+45):290,L=horizontal?120:62,R=55,T=20,B=40,pw=W-L-R,ph=H-T-B;
 const y=n=>T+ph-(n-lo)/(hi-lo)*ph,x=n=>L+(n-lo)/(hi-lo)*pw;
 let svg=`<svg class="pro-plot" viewBox="0 0 ${W} ${H}" role="img" aria-label="${esc(w.title)}" style="font-size:${w.fontSize}px">`;
 if(w.axes||w.grid)for(let i=0;i<=4;i++){const n=lo+(hi-lo)*i/4,px=horizontal?x(n):L,py=horizontal?T:y(n);if(w.grid)svg+=horizontal?`<line x1="${px}" x2="${px}" y1="${T}" y2="${H-B}" class="gridline"/>`:`<line x1="${L}" x2="${W-R}" y1="${py}" y2="${py}" class="gridline"/>`;if(w.axes)svg+=`<text x="${horizontal?px:L-9}" y="${horizontal?H-13:py+4}" text-anchor="${horizontal?'middle':'end'}">${esc(axisNumber(n,hi))}</text>`;}
 if(w.target){svg+=horizontal?`<line x1="${x(w.target)}" x2="${x(w.target)}" y1="${T}" y2="${H-B}" class="target-line"/>`:`<line x1="${L}" x2="${W-R}" y1="${y(w.target)}" y2="${y(w.target)}" class="target-line"/>`;}
 const step=(horizontal?ph:pw)/data.length;
 series.forEach((s,si)=>{if(['line','area'].includes(w.type)){const points=s.values.map((v,i)=>`${L+(i+.5)*step},${y(v??0)}`).join(' ');if(w.type==='area')svg+=`<polygon points="${L+step/2},${y(0)} ${points} ${L+(data.length-.5)*step},${y(0)}" fill="${s.color}" opacity=".10"/>`;svg+=`<polyline points="${points}" fill="none" stroke="${s.color}" stroke-width="2.5"/>`;}
 data.forEach((item,i)=>{const n=s.values[i];if(n===null)return;const bw=Math.min(25,step*.7/series.length),color=si===0?markColor({...item,value:n},w):s.color,cx=L+(i+.5)*step,cy=T+(i+.5)*step;svg+=`<g ${hitAttrs(w,item)}><title>${esc(item.label)} · ${esc(s.name)}: ${esc(numberPro(n,w))}</title>`;
 if(horizontal)svg+=`<rect x="${Math.min(x(0),x(n))}" y="${cy+(si-series.length/2)*bw}" width="${Math.max(.8,Math.abs(x(n)-x(0)))}" height="${Math.max(3,bw-2)}" rx="1" fill="${color}"/>`;
 else if(['line','area'].includes(w.type))svg+=`<circle cx="${cx}" cy="${y(n)}" r="4" fill="${color}"/>`;
 else svg+=`<rect x="${cx+(si-series.length/2)*bw}" y="${Math.min(y(n),y(0))}" width="${Math.max(3,bw-2)}" height="${Math.max(.8,Math.abs(y(n)-y(0)))}" rx="1" fill="${color}"/>`;
 if(w.labels&&series.length<=2)svg+=`<text class="pro-value-label" x="${horizontal?x(n)+5:cx+(si-(series.length-1)/2)*bw}" y="${horizontal?cy+(si-series.length/2)*bw+bw*.7:y(n)-(si%2?19:7)}" text-anchor="${horizontal?'start':'middle'}">${esc(numberPro(n,w.unit==='auto'&&Math.abs(n)>=10000?{...w,unit:Math.abs(n)>=1e6?'mi':'mil',decimals:w.decimals||(Math.abs(n)>=1e6?2:0)}:w))}</text>`;svg+='</g>';});});
 if(w.axes)data.forEach((item,i)=>{const label=w.dimension==='month'?new Date(item.key+'-02T12:00:00').toLocaleDateString('pt-BR',{month:'short',year:'2-digit'}):item.label;svg+=`<text x="${horizontal?L-8:L+(i+.5)*step}" y="${horizontal?T+(i+.5)*step+3:H-14}" text-anchor="${horizontal?'end':'middle'}">${esc(label.length>18?label.slice(0,16)+'…':label)}</text>`;});svg+='</svg>';
 return svg+(w.legend?`<div class="pro-legend">${series.map(s=>`<span><i style="background:${s.color}"></i>${esc(s.name)}</span>`).join('')}${w.target?`<span>Meta: ${numberPro(w.target,w)}</span>`:''}</div>`:'');
}
function proTable(w,data){const cols=w.columns,heads={label:proDimensions[w.dimension],value:valueName(w.value),comparison:valueName(w.comparison),delta:'Diferença'};return `<div class="pro-table-scroll"><table class="studio-table"><thead><tr>${cols.map(c=>`<th>${esc(heads[c])}</th>`).join('')}</tr></thead><tbody>${data.map(r=>`<tr ${hitAttrs(w,r)}>${cols.map(c=>`<td style="${c==='value'?`color:${markColor(r,w)}`:''}">${c==='label'?esc(r.label):numberPro(c==='delta'?r.comparison===null?null:r.value-r.comparison:r[c],w)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function proDonut(w,data){const positive=data.filter(x=>x.value>0),total=positive.reduce((a,x)=>a+x.value,0);if(!total)return '<div class="pro-empty">A rosca precisa de valores positivos.</div>';const C=2*Math.PI*78;let offset=0;return `<svg class="pro-plot" viewBox="0 0 610 270" role="img" aria-label="${esc(w.title)}">${positive.map((r,i)=>{const length=r.value/total*C,old=offset;offset+=length;return `<g ${hitAttrs(w,r)}><circle cx="160" cy="130" r="78" fill="none" stroke="${i%2?w.comparisonColor:markColor(r,w)}" opacity="${Math.max(.3,1-Math.floor(i/2)*.17)}" stroke-width="35" stroke-dasharray="${Math.max(0,length-2)} ${C}" stroke-dashoffset="${-old}" transform="rotate(-90 160 130)"><title>${esc(r.label)}: ${numberPro(r.value,w)}</title></circle>${w.legend?`<text x="290" y="${35+i*24}">${esc(r.label)} ${w.labels?((r.value/total)*100).toFixed(1)+'%':''}</text>`:''}</g>`;}).join('')}${w.labels?`<text x="160" y="132" text-anchor="middle" style="font-size:19px;font-weight:700">${numberPro(total,{...w,unit:w.unit==='auto'?'mil':w.unit})}</text>`:''}</svg>`;}
function proWaterfall(w,data){
const bridge=w.comparison!=='none',base=bridge?data.reduce((a,r)=>a+(r.comparison||0),0):0;let running=base;
const vals=bridge?[{key:'__start',label:valueName(w.comparison),value:base,start:0,end:base}]:[];
for(const r of data){const value=bridge?(r.value||0)-(r.comparison||0):r.value||0,start=running;running+=value;vals.push({...r,value,start,end:running});}
vals.push({key:'__total',label:bridge?valueName(w.value):'Total',value:running,start:0,end:running});
const min=Math.min(0,...vals.flatMap(x=>[x.start,x.end])),max=Math.max(1,...vals.flatMap(x=>[x.start,x.end])),W=640,H=280,L=65,T=30,ph=205,pw=550,y=n=>T+ph-(n-min)/(max-min||1)*ph*.9,step=pw/vals.length;
return '<svg class="pro-plot" viewBox="0 0 '+W+' '+H+'" role="img" aria-label="'+esc(w.title)+'">'+vals.map((r,i)=>'<g '+(!r.key.startsWith('__')?hitAttrs(w,r):'')+'><rect x="'+(L+i*step+step*.15)+'" y="'+y(Math.max(r.start,r.end))+'" width="'+step*.65+'" height="'+Math.max(1,Math.abs(y(r.end)-y(r.start)))+'" fill="'+(r.key.startsWith('__')?w.color:r.value<0?'#078e97':w.conditionColor)+'"><title>'+esc(r.label)+': '+numberPro(r.value,w)+'</title></rect>'+(w.labels?'<text x="'+(L+(i+.5)*step)+'" y="'+(y(Math.max(r.start,r.end))-(i%2?22:8))+'" text-anchor="middle">'+(w.unit==='auto'?axisNumber(r.value,Math.max(Math.abs(r.value),1)):numberPro(r.value,w))+'</text>':'')+(w.axes?'<text x="'+(L+(i+.5)*step)+'" y="267" text-anchor="middle">'+esc(r.label.slice(0,12))+'</text>':'')+'</g>').join('')+'</svg><div class="pro-chart-caption">'+(bridge?'Da comparação ao valor, por variação de cada grupo.':'Soma acumulada de '+esc(valueName(w.value)))+'</div>';
}
function widgetContent(w,page=currentPage(),d=dash()){
 if(w.type==='text')return `<div class="pro-text" data-inline="text">${esc(w.text||'Clique duas vezes para escrever uma observação.')}</div>`;
 if(w.type==='image')return w.image?`<img class="pro-image" src="${w.image}" alt="${esc(w.text||w.title)}" style="object-fit:${w.imageFit}">`:`<button class="pro-image-upload" data-pro="image">${icon('plus')} Escolher uma imagem</button>`;
 if(w.type==='button')return `<div class="pro-button-content"><button class="btn primary" data-pro-navigate="${esc(w.targetPage)}">${esc(w.text||'Abrir página')}</button></div>`;
 if(w.type==='filter'){const field=w.filterDimension,values=[...new Set(sourceRows(d).map(r=>dimValue(r,field)))].sort(),f=w.filterScope==='dashboard'?{area:d.area,period:d.period,categories:d.categories}:page.filters,chosen=field==='category'?f.categories?.[0]:field==='month'?f.period:f.area;return `<label class="pro-filter-content">${proDimensions[field]}<select data-canvas-filter="${w.id}"><option value="">${field==='month'?'Herdar período':'Todos'}</option>${values.map(v=>`<option value="${esc(v)}" ${chosen===v?'selected':''}>${esc(labelValue(v,field))}</option>`).join('')}</select><small>Aplica à ${w.filterScope==='dashboard'?'análise inteira':'página atual'}</small></label>`;}
 if(w.type==='kpi'){const rows=effectiveRows(w,page,d),n=aggregateValue(rows,w.value,w,d),budget=aggregateValue(rows,w.comparison,w,d);return `<div class="pro-kpi" style="color:${markColor({value:n,comparison:budget},w)}"><strong>${numberPro(n,w)}</strong><span>${esc(valueName(w.value))}</span>${w.comparison!=='none'?`<small>${esc(valueName(w.comparison))}: ${numberPro(budget,w)}</small>`:''}</div>`;}
 return proChart(w,page,d);
}
function proWidget(id,page=currentPage(),d=dash(),preview=false){const w=pro(d).widgets[id];if(!w)return '';return `<article class="pro-card ${!preview&&(pro().selected===id||multiSelection.includes(id))?'selected':''}" data-pwidget="${esc(id)}" tabindex="0" style="--span:${w.span};--card-height:${w.height}px;--card-font:${w.fontSize}px;font-family:'${w.font}';color:${w.textColor};background:${w.background};border:${w.border}px solid ${w.borderColor};border-radius:${w.radius}px;padding:${w.padding}px"><div class="pro-card-head">${!preview?`<button class="pro-drag" draggable="true" data-drag-widget="${id}" aria-label="Arrastar ${esc(w.title)}" title="Arraste para organizar">⠿</button>`:''}<h3 data-inline="title" style="font-size:${w.titleSize}px">${esc(w.title)}</h3>${!preview?`<button class="icon-btn" data-pro-duplicate="${id}" aria-label="Duplicar ${esc(w.title)}">⧉</button>`:''}</div>${w.subtitle?`<div class="pro-subtitle">${esc(w.subtitle)}</div>`:''}<div class="pro-card-body">${widgetContent(w,page,d)}</div>${Object.keys(w.filters).length?'<span class="pro-filter-badge">Filtro próprio</span>':''}${!preview?`<button class="pro-resize" data-resize-widget="${id}" aria-label="Redimensionar ${esc(w.title)}" title="Arraste para redimensionar; use as setas quando focado">⌟</button>`:''}</article>`;}
dashboard=function(){const d=dash(),p=pro(),pg=currentPage(),rows=sourceRows(),periods=[...new Set(rows.map(r=>r.date.slice(0,7)))].sort().reverse(),areas=[...new Set(rows.map(r=>r.area))];return `<div class="studio-heading"><div><button class="title-edit" data-action="rename-dashboard"><h1>${esc(d.title)}</h1></button><p>${esc(d.area)} / ${esc(periodLabel(d.period))}</p></div><div class="studio-filters"><label class="studio-filter">Período<select id="period-filter">${periods.map(m=>`<option ${m===d.period?'selected':''} value="${m}">${periodLabel(m)}</option>`).join('')}</select></label><label class="studio-filter">Área<select id="area-filter">${['Todas as áreas',...areas].map(a=>`<option ${a===d.area?'selected':''}>${esc(a)}</option>`).join('')}</select></label></div></div>${shared?'<div class="callout">Snapshot independente · alterações não afetam o original.</div>':''}${studioKpis()}<div class="pro-pagebar"><div class="pro-tabs">${p.pages.map(pg=>`<button data-pro-page="${pg.id}" class="${p.activePage===pg.id?'active':''}">${esc(pg.name)}</button>`).join('')}<button data-pro="add-page" aria-label="Adicionar página">＋</button></div><button class="text-link" data-pro="page-settings">Configurar página</button></div><div class="pro-context"><span>${pg.widgets.length} componentes${multiSelection.length>1?' · '+multiSelection.length+' selecionados':''}</span><div><button data-pro="page-filters">${icon('filter')} Filtros da página${Object.keys(pg.filters).length?' •':''}</button><button data-pro="measures">ƒ Medidas</button><button data-pro="history">${icon('clock')} Versões e modelos</button></div></div>${crossFilter?`<div class="pro-cross">Filtrando por ${proDimensions[crossFilter.dimension]}: <strong>${esc(crossFilter.value)}</strong><button data-pro="clear-cross">Limpar ×</button></div>`:''}${Object.keys(pg.filters).length?'<div class="pro-scope-note">Os filtros desta página substituem os campos correspondentes dos filtros gerais. Os indicadores superiores mostram o recorte geral.</div>':''}${pg.id==='centers'?'<div class="pro-scope-note">Centros de custo ilustrativos: esta base contém categorias. Altere a dimensão após conectar uma fonte com centros reais.</div>':''}<div class="pro-canvas" id="pro-canvas">${pg.widgets.map(id=>proWidget(id)).join('')}</div>${!pg.widgets.length?'<button class="pro-empty-page" data-pro="insert">＋ Adicionar o primeiro componente</button>':''}<div class="studio-page-note">Arraste pelo ícone ⠿ · ajuste pelo canto inferior · Ctrl/Cmd + clique para selecionar vários.</div>`;};
function pSelect(key,label,choices,w,attrs=''){return `<label class="pro-field"><span>${label}</span><select data-pkey="${key}" ${attrs}>${Object.entries(choices).map(([v,name])=>`<option value="${esc(v)}" ${String(w[key])===v?'selected':''}>${esc(name)}</option>`).join('')}</select></label>`;}
function pInput(key,label,w,type='text',attrs=''){return `<label class="pro-field"><span>${label}</span><input data-pkey="${key}" type="${type}" value="${esc(w[key]??'')}" ${attrs}></label>`;}
function pToggle(key,label,w){return `<label class="pro-check"><input data-pkey="${key}" type="checkbox" ${w[key]?'checked':''}>${label}</label>`;}
function section(title,content,open=false){return `<details class="pro-section" ${open?'open':''}><summary>${title}</summary><div>${content}</div></details>`;}
paintProperties=function(){const expanded=$$('#properties details[open]').map(x=>$('summary',x).textContent);const w=currentWidget(),p=pro(),measureChoices={actual:'Realizado',budget:'Orçamento',count:'Registros',...Object.fromEntries(p.measures.map(m=>[m.id,m.name]))};if(!w){$('#properties').innerHTML='<div class="property-title"><strong>Propriedades</strong></div><p class="pro-empty">Adicione ou selecione um componente.</p>';return;}
 const dataTypes=['column','bar','line','area','donut','table','waterfall','kpi'],hasData=dataTypes.includes(w.type);
 let content='';
 if(proTab==='data')content=hasData?`${section('Campos',`<div class="pro-fields-palette">${Object.entries({...proDimensions,...measureChoices}).map(([key,label])=>`<span draggable="true" data-drag-field="${key}" class="field-chip">${esc(label)}</span>`).join('')}</div><p class="property-help">Arraste um campo para um seletor ou escolha na lista.</p>${pSelect('dimension','Eixo / dimensão',proDimensions,w,'data-drop-field="dimension"')}${pSelect('value','Valor',measureChoices,w,'data-drop-field="value"')}${pSelect('comparison','Comparação',{none:'Nenhuma',...measureChoices},w,'data-drop-field="comparison"')}${pSelect('legendField','Séries / legenda',{none:'Realizado × comparação',...proDimensions},w,'data-drop-field="legendField"')}${w.legendField!=='none'?'<p class="property-help">A dimensão cria séries e substitui a comparação neste gráfico.</p>':''}${pSelect('aggregation','Agregação',{sum:'Soma',avg:'Média',count:'Contagem',min:'Mínimo',max:'Máximo'},w)}${w.value.startsWith('m')?'<p class="property-help">Medidas calculadas usam os totais de cada grupo, independentemente da agregação.</p>':''}<button class="text-link" data-pro="measures">＋ Criar medida calculada</button>`,true)}${section('Ordenação e limite',`${pSelect('sort','Ordenar',{label:'Dimensão',desc:'Maior valor primeiro',asc:'Menor valor primeiro'},w)}${pInput('top','Quantidade (0 = todos)',w,'number','min="0" max="50"')}`,true)}${section('Filtros deste componente',`<p class="property-help">Substituem os filtros correspondentes da página e do dashboard.</p>${filterFields(w.filters,'widget')}<button class="text-link" data-pro="reset-widget-filters">Restaurar herança</button>`,true)}`:'<p class="pro-empty">Este componente não utiliza medidas. Configure seu conteúdo na aba Aparência.</p>';
 else if(proTab==='interactions')content=section('Ao clicar em um dado',`${pSelect('interaction','Ação',{none:'Apenas selecionar',filter:'Filtrar os outros gráficos',details:'Abrir registros de origem',navigate:'Navegar para outra página'},w)}${pSelect('targetPage','Página de destino',{'':'Escolha uma página',...Object.fromEntries(p.pages.map(pg=>[pg.id,pg.name]))},w)}<p class="property-help">O filtro cruzado atua na página atual. Clique novamente no mesmo valor para removê-lo.</p>`,true)+section('Atalhos',`<p class="property-help">Clique duas vezes em um título ou texto para editar.<br>Ctrl/Cmd + clique seleciona vários componentes.<br>Use Ctrl/Cmd + Z para desfazer.<br>Foque o canto de redimensionamento e use as setas.</p>`,true);
 else content=`${section('Componente',`${pSelect('type','Tipo',proTypes,w)}${pInput('title','Título',w,'text','maxlength="100"')}${pInput('subtitle','Subtítulo',w,'text','maxlength="200"')}${['text','button','image'].includes(w.type)?`<label class="pro-field"><span>${w.type==='image'?'Descrição acessível':'Conteúdo'}</span><textarea data-pkey="text">${esc(w.text)}</textarea></label>`:''}${w.type==='image'?`<button class="btn" data-pro="image">Escolher imagem</button>${pSelect('imageFit','Enquadramento',{contain:'Mostrar inteira',cover:'Preencher espaço'},w)}`:''}${w.type==='button'?pSelect('targetPage','Página de destino',{'':'Escolha uma página',...Object.fromEntries(p.pages.map(pg=>[pg.id,pg.name]))},w):''}${w.type==='filter'?pSelect('filterDimension','Campo',proDimensions,w)+pSelect('filterScope','Aplicar a',{page:'Página',dashboard:'Dashboard'},w):''}`,true)}${section('Aparência',`${pInput('color','Cor principal',w,'color')}${pInput('comparisonColor','Cor secundária',w,'color')}${pInput('background','Fundo',w,'color')}${pInput('textColor','Texto',w,'color')}${pSelect('font','Fonte',{'Segoe UI':'Segoe UI',Arial:'Arial',Georgia:'Georgia'},w)}${pInput('titleSize','Título (px)',w,'number','min="12" max="30"')}${pInput('fontSize','Texto (px)',w,'number','min="10" max="22"')}`)}${hasData?section('Números e gráfico',`${pSelect('format','Formato',{number:'Número',currency:'Moeda (R$)',percent:'Percentual'},w)}${pSelect('unit','Unidade',{auto:'Inteiro',mil:'Milhares',mi:'Milhões'},w)}${pInput('decimals','Casas decimais',w,'number','min="0" max="4"')}${pToggle('legend','Mostrar legenda',w)}${pToggle('labels','Mostrar rótulos',w)}${pToggle('axes','Mostrar eixos',w)}${pToggle('grid','Mostrar linhas de grade',w)}${pInput('target','Meta (0 = ocultar)',w,'number')}${pSelect('condition','Destaque condicional',{none:'Sem destaque',budget:'Valor acima da comparação',target:'Valor acima da meta'},w)}${pInput('conditionColor','Cor do destaque',w,'color')}${w.type==='table'?`<div class="pro-column-checks">${[['label','Dimensão'],['value','Valor'],['comparison','Comparação'],['delta','Diferença']].map(([k,label])=>`<label><input type="checkbox" data-pro-column="${k}" ${w.columns.includes(k)?'checked':''}>${label}</label>`).join('')}</div>`:''}`,true):''}${section('Tamanho e bordas',`${pInput('span','Largura (3–12 colunas)',w,'number','min="3" max="12"')}${pInput('height','Altura (px)',w,'number','min="180" max="800" step="10"')}${pInput('padding','Espaçamento interno',w,'number','min="0" max="36"')}${pInput('border','Borda (px)',w,'number','min="0" max="4"')}${pInput('borderColor','Cor da borda',w,'color')}${pInput('radius','Cantos (px)',w,'number','min="0" max="24"')}<div class="pro-two"><button class="btn" data-pro="move-before">← Anterior</button><button class="btn" data-pro="move-after">Próximo →</button></div>`)}<div class="pro-two"><button class="btn" data-pro="duplicate">Duplicar</button><button class="btn danger" data-pro="remove">Remover</button></div>`;
 $('#properties').innerHTML=`<div class="property-title"><strong>Propriedades</strong><button class="icon-btn" data-studio="close-inspector" aria-label="Recolher propriedades">${icon('close')}</button></div><div class="property-tabs">${[['data','Dados'],['appearance','Aparência'],['interactions','Interações']].map(([id,title])=>`<button data-pro-tab="${id}" class="${proTab===id?'active':''}">${title}</button>`).join('')}</div><div class="properties-body">${multiSelection.length>1?`<div class="property-note">${multiSelection.length} componentes selecionados. Ajustes visuais e de tamanho serão aplicados a todos.</div>`:''}${content}</div>`;$$('#properties details').forEach(el=>{if(expanded.includes($('summary',el).textContent))el.open=true;});
};
function filterFields(f,scope){const rows=sourceRows(),areas=[...new Set(rows.map(r=>r.area))],months=[...new Set(rows.map(r=>r.date.slice(0,7)))].sort(),cats=[...new Set(rows.map(r=>r.category))];return `<label class="pro-field"><span>Área</span><select data-scope="${scope}" data-filter-key="area"><option value="">Herdar</option><option value="*" ${f.area==='*'?'selected':''}>Todas as áreas</option>${areas.map(v=>`<option ${v===f.area?'selected':''}>${esc(v)}</option>`).join('')}</select></label><label class="pro-field"><span>Período</span><select data-scope="${scope}" data-filter-key="period"><option value="">Herdar</option>${months.map(v=>`<option value="${v}" ${v===f.period?'selected':''}>${periodLabel(v)}</option>`).join('')}</select></label><label class="pro-field"><span>Categorias</span><select multiple size="${Math.min(cats.length+1,6)}" data-scope="${scope}" data-filter-key="categories"><option value="__inherit" ${!f.categories?'selected':''}>Herdar</option><option value="__all" ${f.categories?.length===0?'selected':''}>Todas</option>${cats.map(v=>`<option value="${esc(v)}" ${f.categories?.includes(v)?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`;}
function updateWidget(key,value){const w=currentWidget();if(!w)return;const numeric=['span','height','fontSize','titleSize','padding','radius','border','decimals','top','target'];if(numeric.includes(key))value=Number(value);const ids=multiSelection.length>1&&['color','comparisonColor','background','textColor','borderColor','font','fontSize','titleSize','padding','radius','border','height','span','legend','labels','axes','grid','unit','decimals','format'].includes(key)?multiSelection:[w.id];for(const id of ids)if(pro().widgets[id])pro().widgets[id][key]=value;dash().pro=cleanPro(pro());commitPro();}
selectWidget=function(id,add=false){const p=pro();if(!p.widgets[id])return;p.selected=id;if(add){if(!multiSelection.length)multiSelection=[id];else if(multiSelection.includes(id))multiSelection=multiSelection.filter(x=>x!==id);else multiSelection.push(id);}else multiSelection=[id];$$('[data-pwidget]').forEach(el=>el.classList.toggle('selected',multiSelection.includes(el.dataset.pwidget)));paintProperties();hydrate();persist();};
function addProWidget(type){const p=pro(),id=proId(),w={...proDefaults(),id,type,title:proTypes[type],dimension:['bar','donut','table','waterfall'].includes(type)?'category':'month'};if(['text','image','button','filter','kpi'].includes(type)){w.height=type==='image'?280:200;w.span=type==='kpi'||type==='filter'?3:6;}if(type==='kpi')w.dimension='category';p.widgets[id]=w;currentPage().widgets.push(id);p.selected=id;multiSelection=[id];if($('#modal').open)$('#modal').close();commitPro('Componente adicionado.');openInspector();}
function duplicateWidget(id=currentWidget()?.id,page=currentPage()){if(!id)return;const copy=clonePro(pro().widgets[id]);copy.id=proId();copy.title+=' · cópia';pro().widgets[copy.id]=copy;page.widgets.splice(page.widgets.indexOf(id)+1,0,copy.id);pro().selected=copy.id;multiSelection=[copy.id];commitPro('Componente duplicado.');}
function insertProDialog(){showModal('Adicionar componente',`<div class="insert-grid">${Object.entries(proTypes).map(([type,label])=>`<button class="insert-option" data-pro-add="${type}">${icon(type==='text'?'file':type==='table'?'table':'chart')}<strong>${label}</strong></button>`).join('')}</div>`);}
function pageDialog(){const pg=currentPage();showModal('Configurar página',`<form id="pro-page-form"><label class="form-field">Nome<input name="name" required maxlength="60" value="${esc(pg.name)}"></label><div class="modal-actions"><button type="button" class="btn" data-pro="duplicate-page">Duplicar página</button><button type="button" class="btn danger" data-pro="remove-page" ${pro().pages.length===1?'disabled':''}>Remover</button><button class="btn primary">Salvar</button></div></form>`);}
function moveProWidget(delta){const ids=currentPage().widgets,i=ids.indexOf(pro().selected),j=i+delta;if(j<0||j>=ids.length)return;[ids[i],ids[j]]=[ids[j],ids[i]];commitPro();}
function measuresDialog(){const p=pro();showModal('Medidas calculadas',`<p class="modal-description">Fórmulas calculadas sobre os totais de cada grupo. Use realizado, orcado, registros e parâmetros.</p><div class="pro-measures-list">${p.measures.map(m=>`<div><strong>${esc(m.name)}</strong><code>${esc(m.expression)}</code><button class="text-link" data-pro-edit-measure="${m.id}">Editar</button></div>`).join('')}</div><form id="pro-measure-form"><input type="hidden" name="id" value=""><label class="form-field">Nome<input name="name" required maxlength="70" placeholder="Ex.: Custo por colaborador"></label><label class="form-field">Fórmula<input name="expression" required maxlength="300" placeholder="realizado / colaboradores"></label><div class="pro-formula-suggestions"><button type="button" data-formula="orcado - realizado" data-formula-name="Saldo">Saldo</button><button type="button" data-formula="(realizado - orcado) / orcado * 100" data-formula-name="Desvio percentual">Desvio %</button><button type="button" data-formula="realizado / colaboradores" data-formula-name="Custo por colaborador">Custo por colaborador</button></div><label class="form-field">Formato<select name="format"><option value="number">Número</option><option value="currency">Moeda (R$)</option><option value="percent">Percentual</option></select></label><div id="formula-result" class="property-note">A validação mostrará o resultado para o recorte atual.</div><div class="modal-actions"><button type="button" class="btn" data-pro="validate-formula">Validar fórmula</button><button class="btn primary">Salvar medida</button></div></form><details class="pro-section"><summary>Parâmetros do dashboard</summary><form id="pro-params-form">${Object.entries(p.params).map(([key,val])=>`<label class="pro-field"><span>${esc(key)}</span><input type="number" name="${key}" value="${val}" step="any"></label>`).join('')}<label class="pro-field"><span>Novo parâmetro</span><input name="newKey" placeholder="ex.: unidades" pattern="[a-z][a-z0-9_]{0,30}"></label><label class="pro-field"><span>Valor</span><input name="newValue" type="number" value="1" step="any"></label><button class="btn">Salvar parâmetros</button></form></details>`);}
function validateFormulaForm(){const f=$('#pro-measure-form'),expression=f.elements.expression.value,rows=selectRows(),values={...pro().params,realizado:totals(rows).actual,orcado:totals(rows).budget,registros:rows.length};try{const n=calculateFormula(expression,values);$('#formula-result').textContent='Resultado no recorte: '+n.toLocaleString('pt-BR',{maximumFractionDigits:4});return true;}catch(error){$('#formula-result').textContent=error.message;return false;}}
function snapshotPro(){const d=dash();return clonePro({pro:pro(),title:d.title,period:d.period,area:d.area,categories:d.categories});}
function historyDialog(){state.proVersions||=[];state.proTemplates||=[];showModal('Versões e modelos',`<p class="modal-description">Salvos neste navegador. Uma versão preserva a edição; um modelo reutiliza a estrutura em outra fonte.</p><div class="pro-two"><button class="btn primary" data-pro="save-version">Salvar versão atual</button><button class="btn" data-pro="save-template">Salvar como modelo</button></div><h3 class="pro-modal-heading">Versões desta análise</h3><div class="pro-version-list">${state.proVersions.filter(v=>v.dashboard===dash().id).slice().reverse().map(v=>`<div><span><strong>${esc(v.name)}</strong><small>${new Date(v.date).toLocaleString('pt-BR')} · ${v.snapshot.pro.pages.length} páginas</small></span><button class="btn" data-pro-restore="${v.id}">Restaurar</button></div>`).join('')||'<p>Nenhuma versão salva.</p>'}</div><h3 class="pro-modal-heading">Meus modelos</h3><div class="pro-version-list">${state.proTemplates.map(t=>`<div><span><strong>${esc(t.name)}</strong><small>${t.pro.pages.length} páginas</small></span><button class="btn" data-pro-template="${t.id}">Usar modelo</button></div>`).join('')||'<p>Nenhum modelo salvo.</p>'}</div>`);}
function saveNamedDialog(kind){showModal(kind==='version'?'Salvar versão':'Salvar modelo',`<form id="pro-save-named" data-kind="${kind}"><label class="form-field">Nome<input name="name" required maxlength="80" value="${esc(dash().title)} · ${new Date().toLocaleDateString('pt-BR')}"></label><div class="modal-actions"><button class="btn primary">Salvar</button></div></form>`);}
function imageDialog(){showModal('Inserir imagem',`<p class="modal-description">PNG, JPEG ou WebP, até 1 MB. A imagem é salva junto à análise neste navegador.</p><input id="pro-image-file" type="file" accept="image/png,image/jpeg,image/webp"><div id="pro-image-error" role="status"></div>`);}
function applyHit(id,key){const w=pro().widgets[id];if(!w)return;selectWidget(id);if(w.interaction==='navigate')return choosePage(w.targetPage);if(w.interaction==='none')return;if(w.interaction==='filter'){crossFilter=crossFilter?.origin===id&&crossFilter.value===key?null:{origin:id,dimension:w.dimension,value:key};render();return;}
 const rows=effectiveRows(w).filter(r=>String(dimValue(r,w.dimension))===key);showModal('Registros · '+labelValue(key,w.dimension),`<p class="modal-description">${rows.length} registros no recorte do componente.</p><div class="pro-records"><table class="studio-table"><thead><tr><th>Data</th><th>Área</th><th>Categoria</th><th>Realizado</th><th>Orçamento</th></tr></thead><tbody>${rows.slice(0,100).map(r=>`<tr><td>${esc(r.date)}</td><td>${esc(r.area)}</td><td>${esc(r.category)}</td><td>${money(r.actual)}</td><td>${money(r.budget)}</td></tr>`).join('')}</tbody></table></div>${rows.length>100?'<p>Mostrando os primeiros 100 registros.</p>':''}`);
}
function planAI(text){const n=normalized(text),patch={};if(/barra.*horizont/.test(n))patch.type='bar';else if(/coluna/.test(n))patch.type='column';else if(/linha/.test(n))patch.type='line';else if(/rosca/.test(n))patch.type='donut';else if(/tabela/.test(n))patch.type='table';else if(/area/.test(n)&&!/tecnologia|operac|comercial/.test(n))patch.type='area';
 const amount=n.match(/(?:top|maiores|primeiros)\s*(\d+)/)||n.match(/(\d+)\s*maiores/);if(amount){patch.top=Math.min(50,Number(amount[1]));patch.sort='desc';}else if(/cinco maiores/.test(n)){patch.top=5;patch.sort='desc';}
 if(/vermelh|ultrapass|acima do orcamento/.test(n)){patch.condition='budget';patch.conditionColor='#d44655';}if(/sem legenda|ocult.*legenda/.test(n))patch.legend=false;if(/mostrar legenda/.test(n))patch.legend=true;if(/sem rotulo/.test(n))patch.labels=false;if(/milhao|milhoes/.test(n))patch.unit='mi';if(/milhar/.test(n))patch.unit='mil';if(/pagina inteira|largura total/.test(n))patch.span=12;if(/por categoria/.test(n))patch.dimension='category';if(/por area/.test(n))patch.dimension='area';if(/por mes/.test(n))patch.dimension='month';const title=text.match(/(?:renomeie|t[ií]tulo).*?(?:para|:|como)\s*["“]?(.+?)["”]?$/i);if(title)patch.title=title[1].slice(0,100);return patch;}
studioChat=function(text){if(!text.trim())return;const patch=planAI(text),targets=(multiSelection.length?multiSelection:[currentWidget()?.id]).filter(Boolean);if(Object.keys(patch).length&&targets.length){pendingAI={text,patch,targets};const w=pro().widgets[targets[0]],preview={...w,...patch};showModal('Prévia da alteração sugerida',`<p class="modal-description">${targets.length} componente(s) selecionado(s). Assistente demonstrativo com comandos guiados.</p><div class="pro-ai-preview"><div><strong>Antes · ${esc(w.title)}</strong><div class="pro-preview">${widgetContent(w)}</div></div><div><strong>Depois · ${esc(preview.title)}</strong><div class="pro-preview">${widgetContent(preview)}</div></div></div><div class="property-note">${Object.entries(patch).map(([k,v])=>`${esc(({type:'Tipo',top:'Limite',sort:'Ordem',condition:'Destaque',conditionColor:'Cor',span:'Largura',title:'Título',dimension:'Dimensão',unit:'Unidade',legend:'Legenda',labels:'Rótulos'})[k]||k)}: ${esc(proTypes[v]||({desc:'Maior valor primeiro',asc:'Menor valor primeiro',budget:'Acima da comparação',category:'Categoria',area:'Área',month:'Mês',true:'Sim',false:'Não',mi:'Milhões',mil:'Milhares'})[String(v)]||v)}`).join(' · ')}</div><div class="modal-actions"><button class="btn" data-action="close">Cancelar</button><button class="btn primary" data-pro="apply-ai">Aplicar alterações</button></div>`);return;}
 if(/compare.*mes anterior|explique|variacao|saldo/.test(normalized(text)))return legacyStudioChat(text);
 assistantExpanded=true;dash().messages.push({role:'user',text},{role:'assistant',text:'Nesta demonstração, selecione componentes e peça: “barras horizontais”, “cinco maiores por categoria”, “destaque acima do orçamento em vermelho”, “sem legenda” ou “largura total”. Para fórmulas, use Medidas e os exemplos assistidos.'});commitPro();};
const proActions={insert:insertProDialog,duplicate:()=>duplicateWidget(),image:imageDialog,measures:measuresDialog,history:historyDialog,'save-version':()=>saveNamedDialog('version'),'save-template':()=>saveNamedDialog('template'),'validate-formula':validateFormulaForm,'page-settings':pageDialog,
 'add-page':()=>{const pg={id:proId('p'),name:'Página '+(pro().pages.length+1),widgets:[],filters:{}};pro().pages.push(pg);pro().activePage=pg.id;pro().selected='';multiSelection=[];crossFilter=null;commitPro();pageDialog();},
 'duplicate-page':()=>{const old=currentPage(),pg={id:proId('p'),name:old.name+' · cópia',widgets:[],filters:clonePro(old.filters)};for(const id of old.widgets){const w=clonePro(pro().widgets[id]);w.id=proId();pro().widgets[w.id]=w;pg.widgets.push(w.id);}pro().pages.push(pg);pro().activePage=pg.id;pro().selected=pg.widgets[0]||'';multiSelection=[];$('#modal').close();commitPro('Página duplicada.');},
 'remove-page':()=>{if(pro().pages.length<2)return;const pg=currentPage();for(const id of pg.widgets)delete pro().widgets[id];pro().pages=pro().pages.filter(p=>p.id!==pg.id);pro().activePage=pro().pages[0].id;pro().selected=currentPage().widgets[0]||'';$('#modal').close();multiSelection=[];commitPro('Página removida. Use Desfazer para recuperar.');},
 'page-filters':()=>showModal('Filtros · '+currentPage().name,`${filterFields(currentPage().filters,'page')}<p class="property-help">Alterações são aplicadas ao selecionar. “Herdar” usa o dashboard.</p><div class="modal-actions"><button class="btn" data-pro="reset-page-filters">Restaurar herança</button><button class="btn primary" data-action="close">Concluir</button></div>`),
 'reset-page-filters':()=>{currentPage().filters={};$('#modal').close();commitPro();},'reset-widget-filters':()=>{currentWidget().filters={};commitPro();},
 'clear-cross':()=>{crossFilter=null;render();},'move-before':()=>moveProWidget(-1),'move-after':()=>moveProWidget(1),
 remove:()=>{const ids=multiSelection.length?multiSelection:[currentWidget()?.id];currentPage().widgets=currentPage().widgets.filter(id=>!ids.includes(id));ids.forEach(id=>delete pro().widgets[id]);pro().selected=currentPage().widgets[0]||'';multiSelection=[];commitPro('Removido. Use Desfazer para recuperar.');},
 'apply-ai':()=>{if(!pendingAI)return;for(const id of pendingAI.targets)if(pro().widgets[id])Object.assign(pro().widgets[id],pendingAI.patch);dash().messages.push({role:'user',text:pendingAI.text},{role:'assistant',text:`Alterações aplicadas a ${pendingAI.targets.length} componente(s). Você pode desfazer ou ajustar nas propriedades.`});pendingAI=null;assistantExpanded=true;$('#modal').close();commitPro();}
};
document.addEventListener('click',e=>{
 const b=e.target.closest('button,a'),card=e.target.closest('[data-pwidget]');
 if(b?.dataset.pro){e.preventDefault();e.stopImmediatePropagation();if(card)selectWidget(card.dataset.pwidget);proActions[b.dataset.pro]?.();return;}
 if(b?.dataset.proPage){e.stopImmediatePropagation();choosePage(b.dataset.proPage);return;}
 if(b?.dataset.proTab){e.stopImmediatePropagation();proTab=b.dataset.proTab;paintProperties();return;}
 if(b?.dataset.proAdd){e.stopImmediatePropagation();addProWidget(b.dataset.proAdd);return;}
 if(b?.dataset.proDuplicate){e.stopImmediatePropagation();duplicateWidget(b.dataset.proDuplicate);return;}
 if(b?.hasAttribute('data-pro-navigate')){e.stopImmediatePropagation();if(b.dataset.proNavigate)choosePage(b.dataset.proNavigate);else toast('Escolha uma página de destino nas propriedades.');return;}
 if(b?.dataset.formula){const f=$('#pro-measure-form');f.elements.expression.value=b.dataset.formula;f.elements.name.value=b.dataset.formulaName;f.elements.format.value=b.dataset.formulaName.includes('percentual')?'percent':'currency';validateFormulaForm();return;}
 if(b?.dataset.proEditMeasure){const m=pro().measures.find(m=>m.id===b.dataset.proEditMeasure),f=$('#pro-measure-form');for(const k of ['id','name','expression','format'])f.elements[k].value=m[k];validateFormulaForm();return;}
 if(b?.dataset.proRestore){const v=state.proVersions.find(v=>v.id===b.dataset.proRestore);showModal('Restaurar versão?',`<p class="modal-description">${esc(v.name)} · ${v.snapshot.pro.pages.length} páginas. A configuração atual poderá ser recuperada com Desfazer.</p><div class="modal-actions"><button class="btn" data-action="close">Cancelar</button><button class="btn primary" data-pro-confirm-restore="${v.id}">Restaurar versão</button></div>`);return;}
 if(b?.dataset.proConfirmRestore){const v=state.proVersions.find(v=>v.id===b.dataset.proConfirmRestore);Object.assign(dash(),clonePro(v.snapshot));multiSelection=[];crossFilter=null;$('#modal').close();commitPro('Versão restaurada.');return;}
 if(b?.dataset.proTemplate){const t=state.proTemplates.find(t=>t.id===b.dataset.proTemplate);showModal('Criar análise a partir de modelo',`<form id="pro-use-template" data-template="${t.id}"><label class="form-field">Nome<input name="name" required value="${esc(t.name)}"></label><label class="form-field">Fonte<select name="source"><option value="demo">SAP · demonstração</option>${state.sources.map(s=>`<option value="${esc(s.id)}">${esc(s.name)}</option>`).join('')}</select></label><p class="notes">A estrutura e as medidas serão copiadas. Os filtros serão redefinidos para a fonte escolhida.</p><div class="modal-actions"><button class="btn primary">Criar análise</button></div></form>`);return;}
 const hit=e.target.closest('[data-pro-hit]');if(hit&&!e.ctrlKey&&!e.metaKey){e.stopImmediatePropagation();applyHit(hit.dataset.proHit,hit.dataset.hitValue);return;}
 if(card&&!e.target.closest('input,select,textarea,[contenteditable="true"],[data-resize-widget]')){selectWidget(card.dataset.pwidget,e.ctrlKey||e.metaKey);}
},true);
document.addEventListener('input',e=>{const el=e.target,key=el.dataset.pkey;if(!key||el.matches('select,[type=checkbox],[type=color]'))return;const w=currentWidget();if(!w)return;let val=el.type==='number'?Number(el.value):el.value;if(el.type==='number'&&(!el.value||!Number.isFinite(val)))return;const ids=multiSelection.length>1&&!['title','subtitle','text'].includes(key)?multiSelection:[w.id];for(const id of ids)if(pro().widgets[id])pro().widgets[id][key]=val;dash().pro=cleanPro(pro());for(const id of ids){const card=$(`[data-pwidget="${id}"]`);if(card)card.outerHTML=proWidget(id);}remember();persist();$('#undo-btn').disabled=!undoHistory.length;});
document.addEventListener('change',async e=>{
 const el=e.target;
 if(el.dataset.pkey){e.stopImmediatePropagation();updateWidget(el.dataset.pkey,el.type==='checkbox'?el.checked:el.value);return;}
 if(el.dataset.proColumn){const w=currentWidget();if(el.checked)w.columns.push(el.dataset.proColumn);else w.columns=w.columns.filter(k=>k!==el.dataset.proColumn);if(!w.columns.length)w.columns=['label'];commitPro();return;}
 if(el.dataset.filterKey){const scope=el.dataset.scope,f=scope==='widget'?currentWidget().filters:currentPage().filters,key=el.dataset.filterKey;if(key==='categories'){const values=[...el.selectedOptions].map(x=>x.value);if(values.includes('__inherit'))delete f.categories;else f.categories=values.includes('__all')?[]:values;}else if(el.value)f[key]=el.value;else delete f[key];commitPro();return;}
 if(el.dataset.canvasFilter){const w=pro().widgets[el.dataset.canvasFilter],f=w.filterScope==='page'?currentPage().filters:dash(),key=w.filterDimension==='month'?'period':w.filterDimension==='category'?'categories':'area';if(key==='categories')f.categories=el.value?[el.value]:[];else if(el.value)f[key]=el.value;else if(w.filterScope==='page')delete f[key];else if(key==='area')f.area='Todas as áreas';else f.period=sourceRows().map(r=>r.date.slice(0,7)).sort().at(-1);commitPro();return;}
 if(el.id==='pro-image-file'){const file=el.files[0];if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>1024*1024){$('#pro-image-error').textContent='Escolha PNG, JPEG ou WebP de até 1 MB.';return;}const w=currentWidget(),reader=new FileReader();reader.onload=()=>{w.image=String(reader.result);$('#modal').close();commitPro('Imagem adicionada.');};reader.onerror=()=>$('#pro-image-error').textContent='Não foi possível ler a imagem.';reader.readAsDataURL(file);}
},true);
document.addEventListener('submit',e=>{
 const f=e.target,formId=f.getAttribute('id')||'';if(!formId.startsWith('pro-'))return;e.preventDefault();e.stopImmediatePropagation();const fd=new FormData(f);
 if(formId==='pro-page-form'){currentPage().name=String(fd.get('name')).trim()||'Página';$('#modal').close();commitPro();}
 if(formId==='pro-measure-form'){if(!validateFormulaForm())return;const m={id:fd.get('id')||proId('m'),name:String(fd.get('name')).trim(),expression:String(fd.get('expression')).trim(),format:fd.get('format')},old=pro().measures.findIndex(x=>x.id===m.id);if(old<0)pro().measures.push(m);else pro().measures[old]=m;if(currentWidget()){currentWidget().value=m.id;currentWidget().format=m.format;currentWidget().decimals=m.format==='percent'?1:2;}$('#modal').close();commitPro('Medida salva e aplicada ao componente selecionado.');}
 if(formId==='pro-params-form'){const key=String(fd.get('newKey')).trim();for(const name of Object.keys(pro().params))pro().params[name]=Number(fd.get(name));if(key){if(!/^[a-z][a-z0-9_]{0,30}$/.test(key)||['realizado','orcado','registros','constructor','prototype','__proto__'].includes(key))return toast('Nome de parâmetro inválido ou reservado.');pro().params[key]=Number(fd.get('newValue'));}commitPro('Parâmetros atualizados.');measuresDialog();}
 if(formId==='pro-save-named'){const name=String(fd.get('name')).trim(),kind=f.dataset.kind;if(kind==='version'){state.proVersions||=[];state.proVersions.push({id:proId('v'),dashboard:dash().id,name,date:new Date().toISOString(),snapshot:snapshotPro()});state.proVersions=state.proVersions.slice(-20);}else{state.proTemplates||=[];state.proTemplates.push({id:proId('t'),name,pro:clonePro(pro())});state.proTemplates=state.proTemplates.slice(-20);}commitPro('Salvo neste navegador.');historyDialog();}
 if(formId==='pro-use-template'){const t=state.proTemplates.find(x=>x.id===f.dataset.template),d=defaultDashboard();d.id=proId('d');d.title=String(fd.get('name'));d.source=fd.get('source');d.pro=clonePro(t.pro);d.pro.pages.forEach(pg=>pg.filters={});Object.values(d.pro.widgets).forEach(w=>w.filters={});const rs=sourceRows(d);d.area='Todas as áreas';d.period=rs.map(r=>r.date.slice(0,7)).sort().at(-1)||'2026-09';state.dashboards.push(d);state.current=d.id;$('#modal').close();multiSelection=[];crossFilter=null;commitPro('Análise criada a partir do modelo.');}
},true);
document.addEventListener('dblclick',e=>{const text=e.target.closest('[data-inline]'),card=e.target.closest('[data-pwidget]');if(!text||!card)return;e.stopImmediatePropagation();selectWidget(card.dataset.pwidget);text.contentEditable='true';text.classList.add('editing');text.focus();const selection=getSelection(),range=document.createRange();range.selectNodeContents(text);selection.removeAllRanges();selection.addRange(range);},true);
document.addEventListener('focusout',e=>{const el=e.target;if(!el.matches('[data-inline][contenteditable="true"]'))return;const w=pro().widgets[el.closest('[data-pwidget]').dataset.pwidget];w[el.dataset.inline]=el.textContent.trim().slice(0,el.dataset.inline==='title'?100:4000)||'Sem título';el.contentEditable='false';commitPro();},true);
document.addEventListener('keydown',e=>{if(e.target.isContentEditable){e.stopImmediatePropagation();if(e.key==='Enter'&&e.target.dataset.inline==='title'){e.preventDefault();e.target.blur();}return;}if(e.target.matches('textarea[data-pkey]')){e.stopImmediatePropagation();return;}const resize=e.target.closest('[data-resize-widget]');if(resize&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const w=pro().widgets[resize.dataset.resizeWidget];w.span=Math.max(3,Math.min(12,w.span+(e.key==='ArrowRight'?1:e.key==='ArrowLeft'?-1:0)));w.height=Math.max(180,Math.min(800,w.height+(e.key==='ArrowDown'?20:e.key==='ArrowUp'?-20:0)));commitPro();$(`[data-resize-widget="${w.id}"]`)?.focus();return;}const hit=e.target.closest('[data-pro-hit]');if(hit&&['Enter',' '].includes(e.key)){e.preventDefault();applyHit(hit.dataset.proHit,hit.dataset.hitValue);}},true);
document.addEventListener('dragstart',e=>{const handle=e.target.closest('[data-drag-widget]'),field=e.target.closest('[data-drag-field]');if(handle){draggedWidget=handle.dataset.dragWidget;e.dataTransfer.setData('text/plain',draggedWidget);e.dataTransfer.effectAllowed='move';}if(field){draggedField=field.dataset.dragField;e.dataTransfer.setData('text/plain',draggedField);e.dataTransfer.effectAllowed='copy';}});
document.addEventListener('dragover',e=>{if(draggedWidget&&e.target.closest('[data-pwidget]')||draggedField&&e.target.closest('[data-drop-field]')){e.preventDefault();const card=e.target.closest('[data-pwidget]');$$('.drop-target').forEach(x=>x.classList.remove('drop-target'));card?.classList.add('drop-target');}});
document.addEventListener('drop',e=>{const card=e.target.closest('[data-pwidget]'),field=e.target.closest('[data-drop-field]');if(draggedWidget&&card){e.preventDefault();const list=currentPage().widgets,from=list.indexOf(draggedWidget),to=list.indexOf(card.dataset.pwidget);if(from>=0&&to>=0){list.splice(from,1);list.splice(to,0,draggedWidget);commitPro('Ordem atualizada.');}}else if(draggedField&&field){e.preventDefault();if([...field.options].some(o=>o.value===draggedField))updateWidget(field.dataset.dropField,draggedField);else toast('Esse campo não é compatível com este seletor.');}draggedWidget=null;draggedField=null;$$('.drop-target').forEach(x=>x.classList.remove('drop-target'));});
document.addEventListener('dragend',()=>{draggedWidget=null;draggedField=null;$$('.drop-target').forEach(x=>x.classList.remove('drop-target'));});
document.addEventListener('pointerdown',e=>{const grip=e.target.closest('[data-resize-widget]');if(!grip)return;e.preventDefault();const w=pro().widgets[grip.dataset.resizeWidget],card=grip.closest('[data-pwidget]'),startX=e.clientX,startY=e.clientY,oldSpan=w.span,oldHeight=w.height,unit=$('#pro-canvas').getBoundingClientRect().width/12;grip.setPointerCapture(e.pointerId);function move(ev){w.span=Math.min(12,Math.max(3,oldSpan+Math.round((ev.clientX-startX)/unit)));w.height=Math.max(180,Math.min(800,Math.round((oldHeight+ev.clientY-startY)/10)*10));card.style.setProperty('--span',w.span);card.style.setProperty('--card-height',w.height+'px');}function end(){grip.removeEventListener('pointermove',move);grip.removeEventListener('pointerup',end);grip.removeEventListener('pointercancel',end);commitPro();}grip.addEventListener('pointermove',move);grip.addEventListener('pointerup',end);grip.addEventListener('pointercancel',end);});
studioActions.insert=insertProDialog;studioActions.text=()=>addProWidget('text');studioActions.chart=()=>{openInspector();proTab='appearance';paintProperties();};studioActions.layout=()=>{proTab='appearance';openInspector();paintProperties();toast('Arraste pelo ícone ⠿ ou use Tamanho e bordas para ajustar e reposicionar.');};
function proSlideMarkup(page){return `<div class="pro-deck-title"><span>prometeu / ${esc(dash().title)}</span><h1>${esc(page.name)}</h1><p>${esc(dash().area)} · ${esc(periodLabel(dash().period))}</p></div><div class="pro-canvas">${page.widgets.map(id=>proWidget(id,page,dash(),true)).join('')}</div><p class="slide-source">${esc(sourceName())} · snapshot dos dados e configurações</p>`;}
renderSlide=function(){const pages=pro().pages;proSlide=Math.max(0,Math.min(pages.length-1,proSlide));const el=$('#presentation');el.className='presentation-overlay pro-presentation';el.setAttribute('role','dialog');el.setAttribute('aria-modal','true');el.setAttribute('aria-label','Apresentação do dashboard');el.innerHTML=`<div class="presentation-toolbar"><strong>prometeu / apresentação</strong><div class="actions"><button class="btn" data-action="html">Baixar HTML</button><button class="btn" data-action="exit-presentation">Sair</button></div></div><section class="slide">${proSlideMarkup(pages[proSlide])}</section><div class="slide-controls"><button class="btn" data-action="prev-slide" ${proSlide===0?'disabled':''}>Anterior</button><span>${proSlide+1} / ${pages.length}</span><button class="btn" data-action="next-slide" ${proSlide===pages.length-1?'disabled':''}>Próximo</button></div>`;};
actions['prev-slide']=()=>{proSlide--;renderSlide();};actions['next-slide']=()=>{proSlide++;renderSlide();};
const proPresentationCSS=`*{box-sizing:border-box}body{margin:0;background:#edf2f9;color:#172747;font:14px 'Segoe UI',Arial,sans-serif}header,nav{background:#0b1d51;color:white;padding:15px 4%;display:flex;align-items:center;justify-content:space-between;gap:16px}button{border:1px solid #a9c0e8;background:#1643db;color:white;padding:9px 18px;border-radius:4px;cursor:pointer}button:disabled{opacity:.4}.slide{margin:25px auto;padding:25px;max-width:1350px;background:white}.slide[hidden]{display:none}h1{font-size:30px;margin:10px 0}h3{margin:0}.pro-deck-title{margin-bottom:25px}.pro-deck-title p,.slide-source{color:#7d8fab}.pro-canvas{display:grid;grid-template-columns:repeat(12,minmax(0,1fr));gap:14px}.pro-card{grid-column:span var(--span);height:var(--card-height);display:flex;flex-direction:column;min-width:0}.pro-card-head{display:flex;margin-bottom:10px}.pro-card-body{flex:1;min-height:0;overflow:auto;display:flex;flex-direction:column;font-size:var(--card-font)}.pro-plot{width:100%;height:100%;min-height:0;flex:1}.pro-plot text{fill:currentColor;font-family:inherit;font-size:inherit}.gridline{stroke:#e5eaf3}.target-line{stroke:#c07d32;stroke-dasharray:5 4}.pro-value-label{font-size:10px}.pro-legend{display:flex;justify-content:center;gap:15px;padding:8px;font-size:11px}.pro-legend i{display:inline-block;width:8px;height:8px;margin-right:5px;border-radius:50%}.pro-subtitle{color:#8091ac;font-size:12px;margin-bottom:8px}.pro-text{white-space:pre-wrap;line-height:1.6}.pro-image{width:100%;height:100%;min-height:0}.pro-kpi{margin:auto 0;display:flex;flex-direction:column;gap:8px}.pro-kpi strong{font-size:34px}.pro-button-content{margin:auto;text-align:center}.pro-table-scroll{overflow:auto}table{width:100%;border-collapse:collapse;font-size:12px}td,th{padding:8px;border-bottom:1px solid #e5ebf5;text-align:right}td:first-child,th:first-child{text-align:left}th{background:#edf2f9}.pro-chart-caption,.pro-filter-badge{font-size:11px;color:#8192ad}.pro-filter-content{display:grid;gap:10px}.pro-filter-content select{padding:8px}.pro-filter-content small{color:#8192ad}.pro-empty{padding:30px;text-align:center;color:#8192ad}@media(max-width:700px){.pro-card{grid-column:span 12}.slide{padding:12px;margin:12px}}@media print{body{background:white}header,nav{display:none}.slide,.slide[hidden]{display:block!important;margin:0;break-after:page}.pro-card{break-inside:avoid}.pro-canvas{grid-template-columns:repeat(12,minmax(0,1fr))}}`;
exportHTML=function(){const pages=pro().pages,slides=pages.map((pg,i)=>`<section class="slide" id="${pg.id}" ${i?'hidden':''}>${proSlideMarkup(pg).replaceAll('data-pro-navigate','data-slide-jump').replace(/<select /g,'<select disabled ')}</section>`).join('');const html=`<!doctype html><html lang="pt-BR"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(dash().title)} · Prometeu</title><style>${proPresentationCSS}</style><body><header><strong>prometeu</strong><span>${esc(dash().title)} · Snapshot</span></header>${slides}<nav><button id="prev">Anterior</button><span id="count"></span><button id="next">Próximo</button></nav><script>const pages=[...document.querySelectorAll('.slide')];let n=0;function move(i){n=Math.max(0,Math.min(pages.length-1,i));pages.forEach((p,j)=>p.hidden=j!==n);document.querySelector('#count').textContent=(n+1)+' / '+pages.length;document.querySelector('#prev').disabled=n===0;document.querySelector('#next').disabled=n===pages.length-1;}document.querySelector('#prev').onclick=()=>move(n-1);document.querySelector('#next').onclick=()=>move(n+1);document.addEventListener('keydown',e=>{if(e.key==='ArrowRight')move(n+1);if(e.key==='ArrowLeft')move(n-1)});document.querySelectorAll('[data-slide-jump]').forEach(b=>b.onclick=()=>{const i=pages.findIndex(p=>p.id===b.dataset.slideJump);if(i>=0)move(i)});move(0);<\/script></body></html>`;download('prometeu-apresentacao.html',html,'text/html;charset=utf-8');toast('Todas as páginas foram exportadas em HTML.');};actions.html=exportHTML;
document.addEventListener('keydown',e=>{if($('#presentation').hidden)return;if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();e.stopImmediatePropagation();proSlide+=e.key==='ArrowRight'?1:-1;renderSlide();}},true);
generateLink=function(){if(location.protocol==='file:')return toast('Abra o protótipo em um endereço web para gerar links.');const d=dash(),rows=new Set(selectRows(d,true));for(const pg of pro().pages)for(const id of pg.widgets)for(const row of effectiveRows(pro().widgets[id],pg,d,true))rows.add(row);const payload={dashboard:pickDashboard(d),rows:[...rows]},encoded=btoa(unescape(encodeURIComponent(JSON.stringify(payload)))),url=location.origin+location.pathname+'#dashboard?snapshot='+encodeURIComponent(encoded);if(url.length>45000){$('#share-result').innerHTML='<div class="error">Esta análise contém mais dados ou imagens do que cabe em um link de protótipo. Exporte a apresentação HTML, que inclui todas as páginas.</div>';return;}$('#share-result').innerHTML=`<label class="form-field">Link do snapshot<input id="share-url" readonly value="${esc(url)}"></label><button class="btn" data-action="copy-link">Copiar link</button><p class="notes">Inclui páginas, componentes, medidas, filtros e os dados necessários a cada visualização.</p>`;};actions['generate-link']=generateLink;
let lastProDashboard='';
render=function(){state.dashboards.forEach(d=>pro(d));if(lastProDashboard!==dash().id){multiSelection=[];crossFilter=null;lastProDashboard=dash().id;}legacyStudioRender();const p=pro();$('#tree-pages').innerHTML=p.pages.map(pg=>`<button class="tree-page ${pg.id===p.activePage?'active':''}" data-pro-page="${pg.id}">${icon('file')}${esc(pg.name)}</button>`).join('')+'<button class="tree-page" data-pro="add-page">＋ Nova página</button>';if(location.hash.split('?')[0]==='#dashboard'){paintProperties();const suggestions=$('.assistant-suggestions');if(suggestions)suggestions.innerHTML='<small>Alterações com prévia</small><button data-studio-chat="Barras horizontais com cinco maiores por categoria e destaque acima do orçamento em vermelho">Barras · top 5 · destacar desvios</button><button data-studio-chat="Troque para linhas sem legenda">Linhas sem legenda</button><button data-studio-chat="Explique a variação do saldo">Explicar variação do saldo</button>';}};
state.dashboards.forEach(d=>pro(d));lastSnapshot=JSON.stringify(state);persist();render();
